# Generated by Django 3.0.7 on 2020-07-23 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_v1', '0002_user_details_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_bookmarked_posts', to='api_v1.posts'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='follow_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_follow_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, to='api_v1.following'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='api_v1.likes'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_posts', to='api_v1.posts'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='related_people',
            field=models.ManyToManyField(blank=True, null=True, to='api_v1.related_people'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='stories',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_stories', to='api_v1.stories'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='story_highlights',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_story_highlights', to='api_v1.stories'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='tagged_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_details_tagged_posts', to='api_v1.posts'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user_activity',
            field=models.ManyToManyField(blank=True, null=True, to='api_v1.user_activity'),
        ),
    ]
