# Generated by Django 3.0.7 on 2020-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_auto_20200723_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
