# Generated by Django 3.0.7 on 2020-07-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auto_20200723_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
        migrations.AddField(
            model_name='user_details',
            name='email',
            field=models.EmailField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='nonw', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_details',
            name='username',
            field=models.CharField(default='jsikajs', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
