# Generated by Django 3.0.8 on 2020-08-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_auto_20200803_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='temp_contact_info',
            new_name='tokenised_contact_info',
        ),
    ]
