# Generated by Django 3.0.8 on 2020-08-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_otps_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otps',
            old_name='last_updated',
            new_name='time_created',
        ),
    ]
