# Generated by Django 3.0.8 on 2020-08-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0014_auto_20200804_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otps',
            name='time_created',
            field=models.DateTimeField(),
        ),
    ]
