# Generated by Django 3.0.8 on 2020-09-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0015_auto_20200804_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.user_details')),
            ],
        ),
    ]
