# Generated by Django 3.0.8 on 2020-09-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='showLastsSeen',
            field=models.BooleanField(default=True),
        ),
    ]
