# Generated by Django 3.0.8 on 2020-10-01 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_user_details_showlastsseen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenised_contact_info',
            old_name='key',
            new_name='userToken',
        ),
        migrations.RenameField(
            model_name='user_details',
            old_name='key',
            new_name='userToken',
        ),
        migrations.CreateModel(
            name='sessionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=3000)),
                ('time_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.user_details')),
            ],
        ),
    ]
