# Generated by Django 3.0.8 on 2020-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
