# Generated by Django 3.0.8 on 2020-09-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_v1', '0002_auto_20200924_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_v1.MessageModel', verbose_name='message')),
            ],
        ),
    ]
