# Generated by Django 3.0.8 on 2020-09-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_login_attempts'),
        ('chat_v1', '0003_likedstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedstream',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.user_details', verbose_name='user'),
        ),
    ]
