# Generated by Django 3.0.8 on 2020-09-27 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0016_login_attempts'),
        ('chat_v1', '0004_likedstream_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeNow', models.BooleanField(default=False)),
                ('lastSeen', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.user_details', verbose_name='user')),
            ],
        ),
    ]
