# Generated by Django 3.0.8 on 2020-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_v1', '0005_lastseen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastseen',
            name='activeDevices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lastseen',
            name='lastSeen',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
